home screen test added
F24-Flutter-Run-Tracker/Run-Tracker pull request #23
Opened 2024-09-24 15:13 UTC by MattWay224

home screen test added

2024-09-24 15:34 UTC, MattWay224 commented
Still there is need in fix, cause test cannot find bottomnavigationbar

2024-09-24 15:57 UTC, dinaraparanid requested changes

2024-09-24 15:57 UTC, dinaraparanid commented on test/home_screen_widget_test.dart
> +    expect(find.text('Run Tracker'), findsOneWidget);
Ломается из-за локализации

2024-09-24 16:09 UTC, MattWay224 commented on test/home_screen_widget_test.dart
> +    expect(find.text('Run Tracker'), findsOneWidget);
пофикшу

2024-09-25 12:25 UTC, MattWay224 commented
Still there is need in fix

2024-09-25 20:36 UTC, dinaraparanid approved these changes

2024-09-25 20:37 UTC, merged